server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/plaza_comidas
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      host: localhost
      port: 27017
      database: plaza_comidas

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html