server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/plaza_comidas
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html

